apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sportlink-hpa
  namespace: sportlink
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sportlink-deployment
  minReplicas: 4
  maxReplicas: 7
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
