apiVersion: apps/v1
kind: Deployment
metadata:
  name: sportlink-deployment
  namespace: sportlink
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sportlink 
  template:
    metadata:
      labels:
        app: sportlink
    spec:
      containers:
      - name: sportlink
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        command: ["java"]
        args: ["-jar", "/app/application.jar"]

        env:
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: sportlink-config
                key: SPRING_DATASOURCE_URL
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: sportlink-db-secret
                key: SPRING_DATASOURCE_USERNAME
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sportlink-db-secret
                key: SPRING_DATASOURCE_PASSWORD
      readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 10
          periodSeconds: 10
          
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 30
          periodSeconds: 30